toolbar:
  - styleselect formatselect | bold italic strikethrough forecolor backcolor  | undo redo | image | link
  - alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat
plugins:
  - image
  - link
  - advlist
  - autolink
  - lists
  - charmap
  - print
  - preview
branding:
  - false